name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        id: make_diagram
        uses: githubocto/repo-visualizer@main
        with:
          should_push: false
          excluded_paths: "ignore,.github"
          output_file: "diagram.svg"
          artifact_name: "staticsite-diagram"
      - name: Get Artifact
        uses: actions/upload-artifact@v4
        with:
            name: staticsite-diagram
            path: "downloads"
